import { neon } from "@neondatabase/serverless";
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { firstHeader, recordSecurityEvent, sessionRequiresStepUp } from "../src/server/securityInfrastructure.js";

const COOKIE_NAME = "sc_session";
const MAX_BODY_BYTES = 12_000;
const STEP_UP_TTL_MS = 10 * 60 * 1000;
let sqlClient: ReturnType<typeof neon> | undefined;
function sql(){ if(!sqlClient){ const url=process.env.SMARTCOMMERCE_DATABASE_URL||process.env.DATABASE_URL; if(!url) throw new Error("CUSTOMER_DATABASE_NOT_CONFIGURED"); sqlClient=neon(url);} return sqlClient; }
function hashToken(v:string){return createHash("sha256").update(v).digest("hex");}
function parseCookie(header?:string){const r:Record<string,string>={};for(const p of(header||"").split(";")){const i=p.indexOf("=");if(i<=0)continue;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();try{r[k]=decodeURIComponent(v)}catch{r[k]=v}}return r;}
function sameOrigin(req:any){const o=firstHeader(req.headers?.origin);if(!o)return true;const h=firstHeader(req.headers?.host);if(!h)return false;try{return new URL(o).host===h}catch{return false}}
async function body(req:AsyncIterable<unknown>){const c:Buffer[]=[];let n=0;for await(const x of req){if(x==null)continue;const b=Buffer.isBuffer(x)?x:Buffer.from(String(x));n+=b.length;if(n>MAX_BODY_BYTES){const e=new Error("BODY_TOO_LARGE") as Error&{status?:number};e.status=413;throw e}c.push(b)}return JSON.parse(Buffer.concat(c).toString("utf8")||"{}");}
function send(res:any,s:number,p:unknown){res.statusCode=s;res.end(JSON.stringify(p));}
function encryptionKey(){const secret=process.env.SMARTCOMMERCE_MFA_ENCRYPTION_KEY;if(!secret||secret.length<32)throw new Error("MFA_ENCRYPTION_NOT_CONFIGURED");return createHash("sha256").update(secret).digest();}
function encryptSecret(secret:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv);const ct=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);const tag=cipher.getAuthTag();return `v1.${iv.toString("base64url")}.${tag.toString("base64url")}.${ct.toString("base64url")}`;}
function decryptSecret(value:string){const [v,ivS,tagS,ctS]=value.split(".");if(v!=="v1"||!ivS||!tagS||!ctS)throw new Error("MFA_SECRET_INVALID");const d=createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(ivS,"base64url"));d.setAuthTag(Buffer.from(tagS,"base64url"));return Buffer.concat([d.update(Buffer.from(ctS,"base64url")),d.final()]).toString("utf8");}
const B32="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
function b32encode(bytes:Buffer){let bits=0,val=0,out="";for(const byte of bytes){val=(val<<8)|byte;bits+=8;while(bits>=5){out+=B32[(val>>>(bits-5))&31];bits-=5}}if(bits>0)out+=B32[(val<<(5-bits))&31];return out;}
function b32decode(input:string){let bits=0,val=0;const out:number[]=[];for(const ch of input.replace(/=|\s|-/g,"").toUpperCase()){const idx=B32.indexOf(ch);if(idx<0)continue;val=(val<<5)|idx;bits+=5;if(bits>=8){out.push((val>>>(bits-8))&255);bits-=8}}return Buffer.from(out);}
function totp(secret:string,time=Date.now()){const counter=Math.floor(time/30000);const buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const mac=createHmac("sha1",b32decode(secret)).update(buf).digest();const off=mac[mac.length-1]&15;const num=((mac[off]&127)<<24)|((mac[off+1]&255)<<16)|((mac[off+2]&255)<<8)|(mac[off+3]&255);return String(num%1_000_000).padStart(6,"0");}
function validTotp(secret:string,code:string){if(!/^\d{6}$/.test(code))return false;for(const drift of[-30000,0,30000]){const expected=Buffer.from(totp(secret,Date.now()+drift));const actual=Buffer.from(code);if(expected.length===actual.length&&timingSafeEqual(expected,actual))return true}return false;}
function recoveryHash(code:string){return `sha256:${createHash("sha256").update(code.trim().toUpperCase()).digest("hex")}`;}
function recoveryCodes(){return Array.from({length:10},()=>`${randomBytes(3).toString("hex").toUpperCase()}-${randomBytes(3).toString("hex").toUpperCase()}`);}

export default async function handler(req:any,res:any){
  res.setHeader("Content-Type","application/json");res.setHeader("Cache-Control","no-store");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","same-origin");
  try{
    const token=parseCookie(firstHeader(req.headers?.cookie))[COOKIE_NAME];if(!token)return send(res,401,{error:{code:"AUTH_REQUIRED",message:"Sign in to manage multi-factor authentication."}});
    const tokenHash=hashToken(token);const ids=await sql()`SELECT id,customer_id,auth_level FROM customer_sessions WHERE token_hash=${tokenHash} AND revoked_at IS NULL AND expires_at>NOW() LIMIT 1` as Array<{id:string;customer_id:string;auth_level:string}>;const session=ids[0];if(!session)return send(res,401,{error:{code:"AUTH_REQUIRED",message:"Sign in to manage multi-factor authentication."}});
    const method=String(req.method||"GET").toUpperCase();
    if(method==="GET"){const rows=await sql()`SELECT authenticator_type,status,COUNT(*)::int AS count FROM customer_authenticators WHERE customer_id=${session.customer_id} AND revoked_at IS NULL GROUP BY authenticator_type,status` as Array<{authenticator_type:string;status:string;count:number}>;const active=(type:string)=>rows.filter(r=>r.authenticator_type===type&&r.status==="active").reduce((n,r)=>n+Number(r.count),0);return send(res,200,{totpEnabled:active("totp")>0,recoveryCodesRemaining:active("recovery_code")});}
    if(method!=="POST"){res.setHeader("Allow","GET, POST");return send(res,405,{error:{code:"METHOD_NOT_ALLOWED",message:"GET or POST is required."}})}if(!sameOrigin(req))return send(res,403,{error:{code:"ORIGIN_REJECTED",message:"This request was rejected."}});
    const input=await body(req) as {action?:string;code?:string};const action=String(input.action||"");
    if(action==="totp_begin"){
      if(await sessionRequiresStepUp({tokenHash,maxAuthenticationAgeSeconds:600}))return send(res,403,{error:{code:"STEP_UP_REQUIRED",message:"Confirm your password or passkey before setting up an authenticator app."}});
      const secret=b32encode(randomBytes(20)),enc=encryptSecret(secret),id=`auth_${randomBytes(16).toString("hex")}`;
      await sql()`UPDATE customer_authenticators SET revoked_at=NOW(),status='revoked' WHERE customer_id=${session.customer_id} AND authenticator_type='totp' AND status='disabled' AND revoked_at IS NULL`;
      await sql()`INSERT INTO customer_authenticators(id,customer_id,authenticator_type,status,label,secret_encrypted,created_at) VALUES(${id},${session.customer_id},'totp','disabled','Authenticator app',${enc},NOW())`;
      const account=await sql()`SELECT email FROM customer_accounts WHERE id=${session.customer_id} LIMIT 1` as Array<{email:string}>;const issuer="SmartCommerce";const label=encodeURIComponent(`${issuer}:${account[0]?.email||session.customer_id}`);const uri=`otpauth://totp/${label}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`;
      await recordSecurityEvent({request:req,eventType:"totp_enrollment_started",eventStatus:"pending",riskLevel:"medium",customerId:session.customer_id,sessionId:session.id});
      return send(res,200,{secret,otpauthUri:uri});
    }
    if(action==="totp_confirm"){
      const rows=await sql()`SELECT id,secret_encrypted FROM customer_authenticators WHERE customer_id=${session.customer_id} AND authenticator_type='totp' AND status='disabled' AND revoked_at IS NULL ORDER BY created_at DESC LIMIT 1` as Array<{id:string;secret_encrypted:string}>;const row=rows[0];if(!row||!validTotp(decryptSecret(row.secret_encrypted),String(input.code||"")))return send(res,401,{error:{code:"INVALID_MFA_CODE",message:"That authenticator code could not be verified."}});
      const codes=recoveryCodes();await sql()`UPDATE customer_authenticators SET status='active',last_used_at=NOW() WHERE id=${row.id}`;await sql()`UPDATE customer_authenticators SET revoked_at=NOW(),status='revoked' WHERE customer_id=${session.customer_id} AND authenticator_type='recovery_code' AND revoked_at IS NULL`;
      for(const code of codes){await sql()`INSERT INTO customer_authenticators(id,customer_id,authenticator_type,status,label,secret_encrypted,created_at) VALUES(${`auth_${randomBytes(16).toString("hex")}`},${session.customer_id},'recovery_code','active','Recovery code',${recoveryHash(code)},NOW())`;}
      const expiresAt=new Date(Date.now()+STEP_UP_TTL_MS).toISOString();await sql()`UPDATE customer_sessions SET auth_level='mfa',last_authenticated_at=NOW(),step_up_expires_at=${expiresAt} WHERE id=${session.id}`;await recordSecurityEvent({request:req,eventType:"totp_enabled",eventStatus:"success",riskLevel:"high",customerId:session.customer_id,sessionId:session.id,metadata:{recoveryCodeCount:codes.length}});return send(res,200,{ok:true,recoveryCodes:codes,stepUpExpiresAt:expiresAt});
    }
    if(action==="totp_verify"){
      const rows=await sql()`SELECT secret_encrypted FROM customer_authenticators WHERE customer_id=${session.customer_id} AND authenticator_type='totp' AND status='active' AND revoked_at IS NULL ORDER BY created_at DESC LIMIT 1` as Array<{secret_encrypted:string}>;const row=rows[0];if(!row||!validTotp(decryptSecret(row.secret_encrypted),String(input.code||"")))return send(res,401,{error:{code:"INVALID_MFA_CODE",message:"That authenticator code could not be verified."}});const expiresAt=new Date(Date.now()+STEP_UP_TTL_MS).toISOString();await sql()`UPDATE customer_sessions SET auth_level='mfa',last_authenticated_at=NOW(),step_up_expires_at=${expiresAt} WHERE id=${session.id}`;await recordSecurityEvent({request:req,eventType:"totp_step_up_succeeded",eventStatus:"success",riskLevel:"medium",customerId:session.customer_id,sessionId:session.id});return send(res,200,{ok:true,stepUpExpiresAt:expiresAt});
    }
    if(action==="recovery_verify"){
      const hash=recoveryHash(String(input.code||""));const rows=await sql()`UPDATE customer_authenticators SET revoked_at=NOW(),status='revoked',last_used_at=NOW() WHERE customer_id=${session.customer_id} AND authenticator_type='recovery_code' AND status='active' AND revoked_at IS NULL AND secret_encrypted=${hash} RETURNING id` as Array<{id:string}>;if(!rows.length)return send(res,401,{error:{code:"INVALID_RECOVERY_CODE",message:"That recovery code is invalid or has already been used."}});const expiresAt=new Date(Date.now()+STEP_UP_TTL_MS).toISOString();await sql()`UPDATE customer_sessions SET auth_level='mfa',last_authenticated_at=NOW(),step_up_expires_at=${expiresAt} WHERE id=${session.id}`;await recordSecurityEvent({request:req,eventType:"recovery_code_used",eventStatus:"success",riskLevel:"high",customerId:session.customer_id,sessionId:session.id});return send(res,200,{ok:true,stepUpExpiresAt:expiresAt});
    }
    if(action==="disable_totp"){
      if(await sessionRequiresStepUp({tokenHash,maxAuthenticationAgeSeconds:600})||!['mfa','passkey'].includes(session.auth_level))return send(res,403,{error:{code:"STRONG_STEP_UP_REQUIRED",message:"Use a passkey or authenticator code before disabling multi-factor authentication."}});await sql()`UPDATE customer_authenticators SET revoked_at=NOW(),status='revoked' WHERE customer_id=${session.customer_id} AND authenticator_type IN ('totp','recovery_code') AND revoked_at IS NULL`;await sql()`UPDATE customer_sessions SET auth_level='password',step_up_expires_at=NULL WHERE customer_id=${session.customer_id} AND revoked_at IS NULL`;await recordSecurityEvent({request:req,eventType:"totp_disabled",eventStatus:"success",riskLevel:"critical",customerId:session.customer_id,sessionId:session.id});return send(res,200,{ok:true});
    }
    return send(res,400,{error:{code:"INVALID_ACTION",message:"That MFA action is not supported."}});
  }catch(error){if(error instanceof SyntaxError)return send(res,400,{error:{code:"INVALID_JSON",message:"The request body is invalid."}});if(Number((error as any)?.status)===413)return send(res,413,{error:{code:"REQUEST_TOO_LARGE",message:"The request is too large."}});if(error instanceof Error&&error.message==="MFA_ENCRYPTION_NOT_CONFIGURED")return send(res,503,{error:{code:"MFA_NOT_CONFIGURED",message:"Authenticator-app security is not configured on this environment yet."}});console.error("account_mfa_error",{code:"mfa_request_failed"});return send(res,503,{error:{code:"MFA_UNAVAILABLE",message:"Multi-factor authentication is temporarily unavailable.",retryable:true}});}
}
