import { neon } from "@neondatabase/serverless";
import { createHash, randomBytes } from "node:crypto";
import { firstHeader, recordSecurityEvent } from "../src/server/securityInfrastructure";

const COOKIE_NAME = "sc_session";
const MAX_BODY_BYTES = 12_000;
let sqlClient: ReturnType<typeof neon> | undefined;
function sql(){if(!sqlClient){const url=process.env.SMARTCOMMERCE_DATABASE_URL||process.env.DATABASE_URL;if(!url)throw new Error("COMMERCIAL_DATABASE_NOT_CONFIGURED");sqlClient=neon(url)}return sqlClient}
function hashToken(v:string){return createHash("sha256").update(v).digest("hex")}
function parseCookie(h?:string){const r:Record<string,string>={};for(const p of(h||"").split(";")){const i=p.indexOf("=");if(i<=0)continue;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();try{r[k]=decodeURIComponent(v)}catch{r[k]=v}}return r}
function sameOrigin(req:any){const o=firstHeader(req.headers?.origin);if(!o)return true;const h=firstHeader(req.headers?.host);if(!h)return false;try{return new URL(o).host===h}catch{return false}}
async function body(req:AsyncIterable<unknown>){const c:Buffer[]=[];let n=0;for await(const x of req){if(x==null)continue;const b=Buffer.isBuffer(x)?x:Buffer.from(String(x));n+=b.length;if(n>MAX_BODY_BYTES){const e=new Error("BODY_TOO_LARGE") as Error&{status?:number};e.status=413;throw e}c.push(b)}return JSON.parse(Buffer.concat(c).toString("utf8")||"{}");}
function send(res:any,s:number,p:unknown){res.statusCode=s;res.end(JSON.stringify(p))}
async function context(req:any){const token=parseCookie(firstHeader(req.headers?.cookie))[COOKIE_NAME];if(!token)return undefined;const tokenHash=hashToken(token);const rows=await sql()`SELECT id,customer_id,auth_level,step_up_expires_at FROM customer_sessions WHERE token_hash=${tokenHash} AND revoked_at IS NULL AND expires_at>NOW() LIMIT 1` as Array<{id:string;customer_id:string;auth_level:string;step_up_expires_at:string|Date|null}>;const row=rows[0];if(!row)return undefined;return {...row,strongStepUp:['mfa','passkey'].includes(row.auth_level)&&!!row.step_up_expires_at&&new Date(row.step_up_expires_at).getTime()>Date.now()}}
async function commercialTrust(customerId:string,accountId:string){const rows=await sql()`SELECT m.role,m.authority_status,a.verification_status,a.privilege_status FROM commercial_account_members m JOIN commercial_accounts a ON a.id=m.commercial_account_id WHERE m.customer_id=${customerId} AND m.commercial_account_id=${accountId} AND m.status='active' LIMIT 1` as Array<{role:string;authority_status:string;verification_status:string;privilege_status:string}>;const row=rows[0];if(!row)return undefined;const provider=await sql()`SELECT provider_id FROM commercial_provider_mappings WHERE commercial_account_id=${accountId} AND mapping_status='verified' ORDER BY verified_at DESC NULLS LAST LIMIT 1` as Array<{provider_id:string|null}>;return {...row,providerId:provider[0]?.provider_id||null,verified:row.authority_status==='verified'&&row.verification_status==='verified'&&row.privilege_status==='enabled'&&!!provider[0]}}
async function control(accountId:string,providerId:string|null){const rows=await sql()`SELECT id,control_status,credit_enabled,credit_limit_minor,credit_currency,payment_terms_code,tax_exempt_enabled,tax_exemption_reference,tax_exemption_valid_from,tax_exemption_valid_until,purchase_order_enabled,review_reference,reviewed_at FROM commercial_financial_controls WHERE commercial_account_id=${accountId} AND (provider_id=${providerId} OR provider_id IS NULL) ORDER BY provider_id IS NOT NULL DESC,updated_at DESC LIMIT 1` as Array<any>;return rows[0]}
function taxCurrentlyValid(c:any){if(!c?.tax_exempt_enabled||!c?.tax_exemption_reference)return false;const today=new Date().toISOString().slice(0,10);if(c.tax_exemption_valid_from&&String(c.tax_exemption_valid_from).slice(0,10)>today)return false;if(c.tax_exemption_valid_until&&String(c.tax_exemption_valid_until).slice(0,10)<today)return false;return true}
async function audit(accountId:string,customerId:string,eventType:string,status:string,metadata:Record<string,unknown>={}){await sql()`INSERT INTO commercial_financial_decision_events(id,commercial_account_id,actor_customer_id,event_type,event_status,metadata,created_at) VALUES(${`cfd_${randomBytes(16).toString("hex")}`},${accountId},${customerId},${eventType},${status},${JSON.stringify(metadata)}::jsonb,NOW())`}

export default async function handler(req:any,res:any){
  res.setHeader("Content-Type","application/json");res.setHeader("Cache-Control","no-store");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","same-origin");
  try{
    const session=await context(req);if(!session)return send(res,401,{error:{code:"AUTH_REQUIRED",message:"Sign in to use commercial financial controls."}});
    const method=String(req.method||"GET").toUpperCase();
    if(method==="GET"){
      const accountId=String(req.query?.accountId||"");const trust=await commercialTrust(session.customer_id,accountId);if(!trust)return send(res,404,{error:{code:"COMMERCIAL_ACCOUNT_NOT_FOUND",message:"That commercial account is not available to you."}});const c=await control(accountId,trust.providerId);return send(res,200,{accountId,organisationVerified:trust.verified,strongStepUp:session.strongStepUp,financialControls:c?{status:c.control_status,creditEnabled:c.control_status==='approved'&&!!c.credit_enabled,creditLimitMinor:c.control_status==='approved'&&c.credit_enabled?String(c.credit_limit_minor||""):null,creditCurrency:c.credit_currency||null,paymentTermsCode:c.control_status==='approved'?c.payment_terms_code||null:null,taxExempt:c.control_status==='approved'&&taxCurrentlyValid(c),taxExemptionValidUntil:c.tax_exemption_valid_until||null,purchaseOrderEnabled:c.control_status==='approved'&&!!c.purchase_order_enabled,reviewedAt:c.reviewed_at||null}:null});
    }
    if(method!=="POST"){res.setHeader("Allow","GET, POST");return send(res,405,{error:{code:"METHOD_NOT_ALLOWED",message:"GET or POST is required."}})}if(!sameOrigin(req))return send(res,403,{error:{code:"ORIGIN_REJECTED",message:"This request was rejected."}});
    const input=await body(req) as any;const accountId=String(input.accountId||"");const trust=await commercialTrust(session.customer_id,accountId);if(!trust||!trust.verified){await recordSecurityEvent({request:req,eventType:"commercial_financial_access_blocked",eventStatus:"commercial_not_verified",riskLevel:"high",customerId:session.customer_id,commercialAccountId:accountId||null,sessionId:session.id});return send(res,403,{error:{code:"COMMERCIAL_VERIFICATION_REQUIRED",message:"Verified organisation, verified member authority, enabled privileges, and verified provider mapping are required."}})}
    if(!session.strongStepUp){await recordSecurityEvent({request:req,eventType:"commercial_financial_access_blocked",eventStatus:"strong_step_up_required",riskLevel:"high",customerId:session.customer_id,commercialAccountId:accountId,sessionId:session.id});return send(res,403,{error:{code:"STRONG_STEP_UP_REQUIRED",message:"Confirm with a passkey, authenticator code, or recovery code before using commercial financial privileges."}})}
    const action=String(input.action||"");
    if(action==="evaluate"){
      const capability=String(input.capability||"");const c=await control(accountId,trust.providerId);if(!c||c.control_status!=="approved"){await audit(accountId,session.customer_id,"financial_entitlement_evaluated","blocked",{capability,reason:"control_not_approved"});return send(res,403,{allowed:false,error:{code:"FINANCIAL_CONTROL_NOT_APPROVED",message:"This financial privilege has not been manually approved."}})}
      let allowed=false;let reason="not_enabled";const result:any={capability};
      if(capability==="tax_exemption"){allowed=taxCurrentlyValid(c);reason=allowed?"approved":"tax_exemption_not_valid";result.reference=allowed?c.tax_exemption_reference:null;result.validUntil=allowed?c.tax_exemption_valid_until:null}
      else if(capability==="purchase_order"){allowed=!!c.purchase_order_enabled;reason=allowed?"approved":"purchase_order_not_enabled"}
      else if(capability==="payment_terms"){allowed=!!c.payment_terms_code;reason=allowed?"approved":"payment_terms_not_enabled";result.paymentTermsCode=allowed?c.payment_terms_code:null}
      else if(capability==="credit"){const amount=Number(input.amountMinor);const currency=String(input.currency||"").toUpperCase();allowed=!!c.credit_enabled&&Number.isFinite(amount)&&amount>=0&&!!c.credit_limit_minor&&amount<=Number(c.credit_limit_minor)&&(!c.credit_currency||currency===String(c.credit_currency).toUpperCase());reason=allowed?"within_configured_ceiling":"credit_not_enabled_or_over_ceiling";result.creditLimitMinor=c.credit_enabled?String(c.credit_limit_minor||""):null;result.creditCurrency=c.credit_currency||null;result.requiresOutstandingBalanceCheck=true}
      else return send(res,400,{error:{code:"INVALID_CAPABILITY",message:"That financial capability is not supported."}});
      await audit(accountId,session.customer_id,"financial_entitlement_evaluated",allowed?"allowed":"blocked",{capability,reason});if(!allowed)return send(res,403,{allowed:false,reason});return send(res,200,{allowed:true,reason,...result});
    }
    if(action==="request_override"){
      const type=String(input.overrideType||"");const allowedTypes=['credit_limit_exceed','temporary_credit_increase','tax_exemption_exception','purchase_order_exception','payment_terms_exception'];if(!allowedTypes.includes(type))return send(res,400,{error:{code:"INVALID_OVERRIDE_TYPE",message:"That override request type is not supported."}});const reason=String(input.reason||"").trim();if(reason.length<10||reason.length>1000)return send(res,400,{error:{code:"INVALID_OVERRIDE_REASON",message:"Provide a clear reason for the manual-review request."}});const id=`cfo_${randomBytes(16).toString("hex")}`;const amount=input.requestedAmountMinor===undefined?null:Number(input.requestedAmountMinor);if(amount!==null&&(!Number.isSafeInteger(amount)||amount<0))return send(res,400,{error:{code:"INVALID_OVERRIDE_AMOUNT",message:"The requested amount is invalid."}});await sql()`INSERT INTO commercial_financial_override_requests(id,commercial_account_id,requester_customer_id,override_type,requested_amount_minor,currency,requested_terms_code,reason,override_status,created_at,updated_at) VALUES(${id},${accountId},${session.customer_id},${type},${amount},${String(input.currency||"").trim().toUpperCase()||null},${String(input.requestedTermsCode||"").trim()||null},${reason},'pending_review',NOW(),NOW())`;await audit(accountId,session.customer_id,"financial_override_requested","review_required",{overrideId:id,overrideType:type});await recordSecurityEvent({request:req,eventType:"commercial_financial_override_requested",eventStatus:"pending_manual_review",riskLevel:"high",customerId:session.customer_id,commercialAccountId:accountId,sessionId:session.id,metadata:{overrideId:id,overrideType:type}});return send(res,202,{request:{id,status:"pending_review"},message:"The request is pending authorised manual review. No financial privilege has been changed."});
    }
    return send(res,400,{error:{code:"INVALID_ACTION",message:"That financial-policy action is not supported."}});
  }catch(error){if(error instanceof SyntaxError)return send(res,400,{error:{code:"INVALID_JSON",message:"The request body is invalid."}});if(Number((error as any)?.status)===413)return send(res,413,{error:{code:"REQUEST_TOO_LARGE",message:"The request is too large."}});console.error("commercial_financial_policy_error",{code:"financial_policy_failed"});return send(res,503,{error:{code:"FINANCIAL_POLICY_UNAVAILABLE",message:"Commercial financial controls are temporarily unavailable.",retryable:true}})}
}
