import { useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, CreditCard, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import Container from '../components/shared/Container';
import { approveCommercialFinancialControls, listCommercialAccountReviews, reviewCommercialApplication, type CommercialApplicationReview, verifyCommercialProvider } from '../services/commercialAccountReviewClient';

function money(minor:number|string|null|undefined,currency='JMD'){const n=Number(minor||0)/100;try{return new Intl.NumberFormat('en-JM',{style:'currency',currency}).format(n)}catch{return `${currency} ${n.toFixed(2)}`}}
function stage(a:CommercialApplicationReview){if(a.application_status==='rejected')return 'Rejected';if(a.financial_control_status==='approved')return 'Financial controls approved';if(a.mapping_status==='verified')return 'Provider verified';if(a.verification_status==='verified')return 'Organisation verified';return 'Awaiting review'}
type EvidenceStage='organisation'|'provider'|'finance';

export default function CommercialAccountReviewsPage(){
 const [items,setItems]=useState<CommercialApplicationReview[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [busy,setBusy]=useState('');
 const [references,setReferences]=useState<Record<string,string>>({});const [provider,setProvider]=useState<Record<string,{providerId:string;providerAccountId:string;providerCustomerId:string;providerPriceListId:string;terms:string}>>({});
 const [finance,setFinance]=useState<Record<string,{creditEnabled:boolean;limit:string;currency:string;terms:string;po:boolean}>>({});
 async function load(){setLoading(true);setMessage('');try{setItems((await listCommercialAccountReviews()).applications||[])}catch(e){setMessage(e instanceof Error?e.message:'Commercial applications could not be loaded.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const pending=useMemo(()=>items.filter(x=>['submitted','under_review'].includes(x.application_status)),[items]);
 async function run(key:string,fn:()=>Promise<{applications:CommercialApplicationReview[]}>){setBusy(key);setMessage('');try{const r=await fn();setItems(r.applications||[]);setMessage('Commercial account state updated.')}catch(e){setMessage(e instanceof Error?e.message:'The commercial account could not be updated.')}finally{setBusy('')}}
 function evidenceKey(stageName:EvidenceStage,id:string){return `${stageName}:${id}`} function evidence(stageName:EvidenceStage,id:string){return references[evidenceKey(stageName,id)]||''} function setEvidence(stageName:EvidenceStage,id:string,v:string){const k=evidenceKey(stageName,id);setReferences(x=>({...x,[k]:v}))}
 function p(a:CommercialApplicationReview){return provider[a.commercial_account_id]||{providerId:a.provider_id||'',providerAccountId:a.provider_account_id||'',providerCustomerId:a.provider_customer_id||'',providerPriceListId:a.provider_price_list_id||'',terms:a.payment_terms_code||''}}
 function f(a:CommercialApplicationReview){return finance[a.commercial_account_id]||{creditEnabled:!!a.credit_enabled,limit:a.credit_limit_minor?String(a.credit_limit_minor):'',currency:a.credit_currency||'JMD',terms:a.payment_terms_code||'',po:!!a.purchase_order_enabled}}
 return <div className="demo-page sc-operations-page"><Container>
  <header className="demo-page-heading"><span className="sc-flow-kicker">Commercial operations</span><h1>Commercial account activation</h1><p>Review organisation claims, bind the verified provider account, then approve financial privileges separately. No account receives credit merely because the organisation was verified.</p><button type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/> Refresh</button></header>
  <section className="demo-stats-grid"><article><strong>{pending.length}</strong><span>Awaiting organisation review</span></article><article><strong>{items.filter(x=>x.verification_status==='verified'&&x.mapping_status!=='verified').length}</strong><span>Need provider mapping</span></article><article><strong>{items.filter(x=>x.mapping_status==='verified'&&x.financial_control_status!=='approved').length}</strong><span>Need financial decision</span></article><article><strong>{items.filter(x=>x.financial_control_status==='approved').length}</strong><span>Financially configured</span></article></section>
  {message?<p className="sc-flow-status" role="status">{message}</p>:null}{loading?<p>Loading commercial applications…</p>:null}
  <div className="sc-operations-stack">{items.map(a=>{const pv=p(a),fc=f(a),key=a.application_id;return <article className="demo-flow-form" key={key}>
   <div className="sc-commercial-review-heading"><Building2/><div><span className="sc-flow-kicker">{stage(a)}</span><h2>{a.display_name}</h2><p>{a.legal_name} · {a.claimed_account_type} · applicant {a.applicant_name} ({a.applicant_email})</p></div></div>
   {a.risk_flags?.length?<p className="sc-flow-status is-error">Review flags: {a.risk_flags.join(', ')}</p>:null}
   <div className="demo-stats-grid"><article><strong>{a.application_status}</strong><span>Application</span></article><article><strong>{a.verification_status}</strong><span>Organisation</span></article><article><strong>{a.mapping_status||'not mapped'}</strong><span>Provider</span></article><article><strong>{a.financial_control_status||'not approved'}</strong><span>Financial controls</span></article></div>
   {['submitted','under_review'].includes(a.application_status)?<fieldset><legend><ShieldCheck size={16}/> Organisation verification</legend><label>Organisation review reference<input value={evidence('organisation',key)} onChange={e=>setEvidence('organisation',key,e.target.value)} placeholder="Internal approval or evidence reference"/></label><div className="sc-form-actions"><button type="button" disabled={!!busy} onClick={()=>void run(`approve-${key}`,()=>reviewCommercialApplication({applicationId:key,reviewAction:'approve',reviewReference:evidence('organisation',key)}))}><CheckCircle2 size={16}/> Verify organisation</button><button type="button" className="secondary" disabled={!!busy} onClick={()=>void run(`reject-${key}`,()=>reviewCommercialApplication({applicationId:key,reviewAction:'reject',reviewReference:evidence('organisation',key)}))}><XCircle size={16}/> Reject</button></div></fieldset>:null}
   {a.verification_status==='verified'?<fieldset><legend><ShieldCheck size={16}/> Provider account verification</legend><label>Provider ID<input value={pv.providerId} onChange={e=>setProvider(x=>({...x,[a.commercial_account_id]:{...pv,providerId:e.target.value}}))}/></label><label>Provider account ID<input value={pv.providerAccountId} onChange={e=>setProvider(x=>({...x,[a.commercial_account_id]:{...pv,providerAccountId:e.target.value}}))}/></label><label>Provider customer ID<input value={pv.providerCustomerId} onChange={e=>setProvider(x=>({...x,[a.commercial_account_id]:{...pv,providerCustomerId:e.target.value}}))}/></label><label>Price list ID<input value={pv.providerPriceListId} onChange={e=>setProvider(x=>({...x,[a.commercial_account_id]:{...pv,providerPriceListId:e.target.value}}))}/></label><label>Payment terms code<input value={pv.terms} onChange={e=>setProvider(x=>({...x,[a.commercial_account_id]:{...pv,terms:e.target.value}}))}/></label><label>Provider verification reference<input value={evidence('provider',key)} onChange={e=>setEvidence('provider',key,e.target.value)} placeholder="Provider evidence or mapping reference"/></label><button type="button" disabled={!!busy} onClick={()=>void run(`provider-${key}`,()=>verifyCommercialProvider({accountId:a.commercial_account_id,providerId:pv.providerId,providerAccountId:pv.providerAccountId,providerCustomerId:pv.providerCustomerId,providerPriceListId:pv.providerPriceListId,paymentTermsCode:pv.terms,verificationReference:evidence('provider',key)}))}>Verify provider mapping</button></fieldset>:null}
   {a.mapping_status==='verified'?<fieldset><legend><CreditCard size={16}/> Financial privileges</legend><p>Organisation verification does not grant credit. Record an authorised financial decision here.</p><label><input type="checkbox" checked={fc.creditEnabled} onChange={e=>setFinance(x=>({...x,[a.commercial_account_id]:{...fc,creditEnabled:e.target.checked}}))}/> Enable account credit</label>{fc.creditEnabled?<><label>Credit limit (minor units)<input inputMode="numeric" value={fc.limit} onChange={e=>setFinance(x=>({...x,[a.commercial_account_id]:{...fc,limit:e.target.value}}))}/></label><label>Currency<input value={fc.currency} maxLength={3} onChange={e=>setFinance(x=>({...x,[a.commercial_account_id]:{...fc,currency:e.target.value.toUpperCase()}}))}/></label></>:null}<label>Payment terms<input value={fc.terms} onChange={e=>setFinance(x=>({...x,[a.commercial_account_id]:{...fc,terms:e.target.value}}))}/></label><label><input type="checkbox" checked={fc.po} onChange={e=>setFinance(x=>({...x,[a.commercial_account_id]:{...fc,po:e.target.checked}}))}/> Purchase orders allowed</label><label>Financial approval reference<input value={evidence('finance',key)} onChange={e=>setEvidence('finance',key,e.target.value)} placeholder="Credit committee or financial approval reference"/></label>{a.financial_control_status==='approved'?<p className="sc-flow-status is-success">Current approved credit: {a.credit_enabled?money(a.credit_limit_minor,a.credit_currency||'JMD'):'disabled'} · PO {a.purchase_order_enabled?'enabled':'disabled'}</p>:null}<button type="button" disabled={!!busy} onClick={()=>void run(`finance-${key}`,()=>approveCommercialFinancialControls({accountId:a.commercial_account_id,providerId:pv.providerId||undefined,creditEnabled:fc.creditEnabled,creditLimitMinor:fc.creditEnabled?Number(fc.limit):undefined,creditCurrency:fc.currency,paymentTermsCode:fc.terms||undefined,purchaseOrderEnabled:fc.po,reviewReference:evidence('finance',key)}))}>Approve financial controls</button></fieldset>:null}
  </article>})}</div>
 </Container></div>
}
