import { AlertTriangle, CheckCircle2, Loader2, Mail, MessageCircle, Smartphone } from "lucide-react";
import { useEffect, useState } from "react";
import Container from "../components/shared/Container";
import { getStaffSession, loginStaff, logoutStaff, type StaffSessionSummary } from "../services/deliveryReviewClient";

type ChannelState={enabled:boolean;ready:boolean;[key:string]:boolean};
type Health={providers:{email:ChannelState;sms:ChannelState;whatsapp:ChannelState};phoneVerificationAvailable:boolean;checkedAt:string};
async function loadHealth(){const response=await fetch("/api/delivery-notification-health",{credentials:"same-origin",headers:{Accept:"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||"Notification readiness could not be loaded.");return payload as Health;}

function Channel({title,icon,state}:{title:string;icon:React.ReactNode;state:ChannelState}){const missing=Object.entries(state).filter(([key,value])=>key!=="ready"&&key!=="enabled"&&!value).map(([key])=>key);return <article className={`sc-notification-health-card ${state.ready?"is-ready":"is-incomplete"}`}><div>{icon}<div><strong>{title}</strong><span>{state.ready?"Ready for external delivery":"Configuration incomplete"}</span></div>{state.ready?<CheckCircle2/>:<AlertTriangle/>}</div><dl><div><dt>Channel enabled</dt><dd>{state.enabled?"Yes":"No"}</dd></div><div><dt>Overall readiness</dt><dd>{state.ready?"Ready":"Blocked"}</dd></div></dl>{missing.length?<p>Missing: {missing.join(", ")}</p>:null}</article>}

export default function DeliveryNotificationHealthPage(){
  const[staff,setStaff]=useState<StaffSessionSummary|null>(null);const[checking,setChecking]=useState(true);const[username,setUsername]=useState("");const[password,setPassword]=useState("");const[loginError,setLoginError]=useState("");const[health,setHealth]=useState<Health|null>(null);const[error,setError]=useState("");
  useEffect(()=>{let active=true;getStaffSession().then(result=>{if(active)setStaff(result.authenticated?result.staff:null)}).catch(()=>{if(active)setStaff(null)}).finally(()=>{if(active)setChecking(false)});return()=>{active=false};},[]);
  useEffect(()=>{if(!staff)return;setError("");loadHealth().then(setHealth).catch((err:any)=>setError(err?.message||"Readiness check failed."));},[staff]);
  async function signIn(event:React.FormEvent){event.preventDefault();setLoginError("");try{const result=await loginStaff({username:username.trim(),password});setStaff(result.staff);setPassword("");}catch(err:any){setLoginError(err?.message||"Staff sign-in failed.");}}
  async function signOut(){await logoutStaff().catch(()=>undefined);setStaff(null);setHealth(null);}
  if(checking)return <div className="demo-page"><Container className="demo-page-content"><div className="demo-empty"><Loader2 className="sc-spin"/><h2>Checking staff access…</h2></div></Container></div>;
  if(!staff)return <div className="demo-page"><Container className="demo-page-content"><section className="sc-delivery-ops-login"><h1>Notification readiness</h1><p>Sign in with your Total Tools POS staff credentials.</p><form onSubmit={signIn}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{loginError?<p role="alert">{loginError}</p>:null}<button type="submit">Sign in</button></form></section></Container></div>;
  return <div className="demo-page"><section className="demo-page-hero"><Container><span>Operations</span><h1>Notification readiness</h1><p>See whether delivery email, SMS and WhatsApp are actually configured. This page never exposes provider secrets.</p></Container></section><Container className="demo-page-content"><div className="sc-notification-health-toolbar"><span>{staff.firstName||staff.username}</span><button onClick={signOut}>Sign out</button></div>{error?<p role="alert">{error}</p>:null}{health?<><div className="sc-notification-health-grid"><Channel title="Email" icon={<Mail/>} state={health.providers.email}/><Channel title="SMS" icon={<Smartphone/>} state={health.providers.sms}/><Channel title="WhatsApp" icon={<MessageCircle/>} state={health.providers.whatsapp}/></div><div className="sc-notification-health-note"><strong>Phone verification</strong><span>{health.phoneVerificationAvailable?"Available":"Not implemented yet — SMS and WhatsApp remain customer-gated."}</span><small>Checked {new Date(health.checkedAt).toLocaleString()}</small></div></>:null}</Container></div>;
}
