import { CheckCircle2, CircleAlert, Clock3, Loader2, LogOut, PackageCheck, RefreshCw, ShieldCheck, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import Container from "../components/shared/Container";
import { getStaffSession, loginStaff, logoutStaff, type StaffSessionSummary } from "../services/deliveryReviewClient";
import { listStaffDeliveries, updateStaffDelivery, type DeliveryProofMethod, type DeliveryStatus, type StaffDelivery } from "../services/deliveryLifecycleClient";
import "../styles/delivery-operations.css";

const labels:Record<DeliveryStatus,string>={order_received:"Order received",preparing:"Preparing",ready_for_collection:"Ready for collection",dispatched:"Dispatched",out_for_delivery:"Out for delivery",delivered:"Delivered",collected:"Collected",exception:"Exception"};
const nextByStatus:Record<DeliveryStatus,DeliveryStatus[]>={order_received:["preparing","ready_for_collection","dispatched","exception"],preparing:["ready_for_collection","dispatched","exception"],ready_for_collection:["collected","exception"],dispatched:["out_for_delivery","delivered","exception"],out_for_delivery:["delivered","exception"],delivered:[],collected:[],exception:["preparing","ready_for_collection","dispatched","out_for_delivery"]};
const proofLabels:Record<DeliveryProofMethod,string>={recipient_acknowledgement:"Recipient acknowledgement",signed_docket:"Signed delivery docket",photo_evidence:"Photo evidence",courier_confirmation:"Courier confirmation",collection_receipt:"Collection receipt"};

function defaultMessage(status:DeliveryStatus){
  const map:Record<DeliveryStatus,string>={order_received:"Order received and awaiting fulfilment preparation.",preparing:"Your order is being prepared for fulfilment.",ready_for_collection:"Your order is ready for collection.",dispatched:"Your order has been dispatched.",out_for_delivery:"Your order is out for delivery.",delivered:"Your order has been delivered.",collected:"Your order has been collected.",exception:"Your order requires additional delivery attention."};
  return map[status];
}

export default function DeliveryOperationsPage(){
  const [staff,setStaff]=useState<StaffSessionSummary|null>(null);const[checking,setChecking]=useState(true);const[username,setUsername]=useState("");const[password,setPassword]=useState("");const[loginError,setLoginError]=useState("");
  const[deliveries,setDeliveries]=useState<StaffDelivery[]>([]);const[statusFilter,setStatusFilter]=useState("all");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[savingId,setSavingId]=useState("");
  const[drafts,setDrafts]=useState<Record<string,{status:DeliveryStatus;publicMessage:string;internalNote:string;trackingReference:string;scheduledFor:string;exceptionMessage:string;proofRecipientName:string;proofMethod:DeliveryProofMethod;proofReference:string;proofNotes:string}>>({});

  useEffect(()=>{let active=true;getStaffSession().then(result=>{if(active)setStaff(result.authenticated?result.staff:null)}).catch(()=>{if(active)setStaff(null)}).finally(()=>{if(active)setChecking(false)});return()=>{active=false};},[]);
  async function refresh(next=statusFilter){if(!staff)return;setLoading(true);setError("");try{const result=await listStaffDeliveries(next);setDeliveries(result.deliveries||[]);}catch(err:any){setError(err?.message||"Delivery operations could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{if(staff)void refresh(statusFilter)},[staff,statusFilter]);
  async function signIn(event:React.FormEvent){event.preventDefault();setLoginError("");try{const result=await loginStaff({username:username.trim(),password});setStaff(result.staff);setPassword("");}catch(err:any){setLoginError(err?.message||"Staff sign-in failed.");}}
  async function signOut(){await logoutStaff().catch(()=>undefined);setStaff(null);setDeliveries([]);}
  function draftFor(delivery:StaffDelivery){return drafts[delivery.order_id]||{status:(nextByStatus[delivery.status]?.[0]||delivery.status),publicMessage:defaultMessage(nextByStatus[delivery.status]?.[0]||delivery.status),internalNote:"",trackingReference:delivery.tracking_reference||"",scheduledFor:delivery.scheduled_for?new Date(delivery.scheduled_for).toISOString().slice(0,16):"",exceptionMessage:"",proofRecipientName:"",proofMethod:"recipient_acknowledgement" as DeliveryProofMethod,proofReference:"",proofNotes:""};}
  function patch(orderId:string,key:string,value:string,delivery:StaffDelivery){setDrafts(current=>({...current,[orderId]:{...draftFor(delivery),...(current[orderId]||{}),[key]:value}}));}
  async function save(delivery:StaffDelivery){const draft=draftFor(delivery);const terminal=draft.status==="delivered"||draft.status==="collected";if(terminal&&!draft.proofRecipientName.trim()){setError("Record who received or collected the order before completing it.");return;}if(terminal&&draft.proofMethod!=="recipient_acknowledgement"&&!draft.proofReference.trim()){setError("Add the proof reference for the selected completion method.");return;}setSavingId(delivery.order_id);setError("");try{await updateStaffDelivery({orderId:delivery.order_id,status:draft.status,publicMessage:draft.publicMessage.trim()||defaultMessage(draft.status),internalNote:draft.internalNote.trim()||undefined,trackingReference:draft.trackingReference.trim()||undefined,scheduledFor:draft.scheduledFor?new Date(draft.scheduledFor).toISOString():undefined,exceptionMessage:draft.exceptionMessage.trim()||undefined,proofRecipientName:draft.proofRecipientName.trim()||undefined,proofMethod:terminal?draft.proofMethod:undefined,proofReference:draft.proofReference.trim()||undefined,proofNotes:draft.proofNotes.trim()||undefined});setDrafts(current=>{const next={...current};delete next[delivery.order_id];return next});await refresh();}catch(err:any){setError(err?.message||"Delivery status could not be updated.");}finally{setSavingId("");}}
  const activeCount=useMemo(()=>deliveries.filter(d=>!["delivered","collected"].includes(d.status)).length,[deliveries]);

  if(checking)return <div className="sc-delivery-ops-page"><Container><div className="sc-delivery-ops-loading"><Loader2 className="sc-spin"/> Checking staff access…</div></Container></div>;
  if(!staff)return <div className="sc-delivery-ops-page"><Container className="sc-delivery-ops-shell"><section className="sc-delivery-ops-login"><div><ShieldCheck size={18}/> Internal dispatch</div><h1>Delivery operations</h1><p>Sign in with your Total Tools POS staff credentials to manage dispatch and collection statuses.</p><form onSubmit={signIn}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} required autoComplete="username"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required autoComplete="current-password"/></label>{loginError?<p role="alert">{loginError}</p>:null}<button type="submit">Sign in to dispatch</button></form></section></Container></div>;

  return <div className="sc-delivery-ops-page"><Container className="sc-delivery-ops-shell">
    <header className="sc-delivery-ops-header"><div><span><Truck size={18}/> Fulfilment control</span><h1>Delivery operations</h1><p>Move verified orders through preparation, dispatch, collection and proof-of-completion.</p></div><div><span>{staff.firstName||staff.username}{staff.role?` · ${staff.role}`:""}</span><button onClick={signOut}><LogOut size={16}/> Sign out</button></div></header>
    <section className="sc-delivery-ops-toolbar"><div><button className={statusFilter==="all"?"is-active":""} onClick={()=>setStatusFilter("all")}>All</button><button className={statusFilter==="order_received"?"is-active":""} onClick={()=>setStatusFilter("order_received")}>New</button><button className={statusFilter==="preparing"?"is-active":""} onClick={()=>setStatusFilter("preparing")}>Preparing</button><button className={statusFilter==="dispatched"?"is-active":""} onClick={()=>setStatusFilter("dispatched")}>Dispatched</button><button className={statusFilter==="out_for_delivery"?"is-active":""} onClick={()=>setStatusFilter("out_for_delivery")}>Out</button><button className={statusFilter==="exception"?"is-active":""} onClick={()=>setStatusFilter("exception")}>Exceptions</button></div><button onClick={()=>void refresh()} disabled={loading}><RefreshCw size={16} className={loading?"sc-spin":""}/> Refresh</button></section>
    <div className="sc-delivery-ops-kpi"><PackageCheck size={18}/><strong>{activeCount}</strong><span>active fulfilment record{activeCount===1?"":"s"} in this view</span></div>
    {error?<p className="sc-delivery-ops-error" role="alert">{error}</p>:null}
    {!loading&&!deliveries.length?<section className="sc-delivery-ops-empty"><CheckCircle2/><strong>No deliveries in this state.</strong><span>New verified orders will appear automatically from the authoritative commercial ledger.</span></section>:null}
    <div className="sc-delivery-ops-list">{deliveries.map(delivery=>{const draft=draftFor(delivery);const done=["delivered","collected"].includes(delivery.status);return <article key={delivery.order_id} className="sc-delivery-ops-card">
      <div className="sc-delivery-ops-card__head"><div><span>{delivery.fulfilment_mode==="pickup"?"Collection":"Delivery"}</span><strong>{delivery.order_id}</strong><small>{delivery.provider||"Internal fulfilment"}{delivery.service_label?` · ${delivery.service_label}`:""}</small></div><div className={`sc-delivery-ops-status is-${delivery.status}`}>{delivery.status==="exception"?<CircleAlert size={14}/>:null}{labels[delivery.status]}</div></div>
      {delivery.collection_point_name?<p className="sc-delivery-ops-collection">Collection point: {delivery.collection_point_name}</p>:null}
      {done?<div className="sc-delivery-ops-complete"><CheckCircle2 size={18}/><div><strong>{labels[delivery.status]}</strong><span>{delivery.proof_recipient_name?`Completed with ${delivery.proof_recipient_name}`:"Completion recorded"}{delivery.proof_method?` · ${proofLabels[delivery.proof_method]}`:""}{delivery.completed_at?` · ${new Date(delivery.completed_at).toLocaleString()}`:""}</span></div></div>:<div className="sc-delivery-ops-form">
        <label>Next status<select value={draft.status} onChange={e=>{const value=e.target.value as DeliveryStatus;patch(delivery.order_id,"status",value,delivery);patch(delivery.order_id,"publicMessage",defaultMessage(value),delivery)}}>{nextByStatus[delivery.status].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>
        <label>Tracking reference<input value={draft.trackingReference} onChange={e=>patch(delivery.order_id,"trackingReference",e.target.value,delivery)} placeholder="Courier / internal tracking ref"/></label>
        <label>Scheduled time<input type="datetime-local" value={draft.scheduledFor} onChange={e=>patch(delivery.order_id,"scheduledFor",e.target.value,delivery)}/></label>
        <label className="is-wide">Customer-facing update<textarea rows={2} value={draft.publicMessage} onChange={e=>patch(delivery.order_id,"publicMessage",e.target.value,delivery)}/></label>
        {draft.status==="exception"?<label className="is-wide">Exception message<textarea rows={2} value={draft.exceptionMessage} onChange={e=>patch(delivery.order_id,"exceptionMessage",e.target.value,delivery)} placeholder="What needs attention?"/></label>:null}
        {(draft.status==="delivered"||draft.status==="collected")?<><label>Received / collected by<input value={draft.proofRecipientName} onChange={e=>patch(delivery.order_id,"proofRecipientName",e.target.value,delivery)} required/></label><label>Proof method<select value={draft.proofMethod} onChange={e=>patch(delivery.order_id,"proofMethod",e.target.value,delivery)}>{Object.entries(proofLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="is-wide">Proof reference {draft.proofMethod==="recipient_acknowledgement"?<span>(optional)</span>:null}<input value={draft.proofReference} onChange={e=>patch(delivery.order_id,"proofReference",e.target.value,delivery)} placeholder="Signature, image, docket, courier or receipt reference"/></label><label className="is-wide">Proof notes<textarea rows={2} value={draft.proofNotes} onChange={e=>patch(delivery.order_id,"proofNotes",e.target.value,delivery)} placeholder="Completion details"/></label></>:null}
        <label className="is-wide">Internal note<textarea rows={2} value={draft.internalNote} onChange={e=>patch(delivery.order_id,"internalNote",e.target.value,delivery)} placeholder="Staff-only dispatch note"/></label>
        <button className="is-wide" onClick={()=>void save(delivery)} disabled={savingId===delivery.order_id}>{savingId===delivery.order_id?<><Loader2 size={16} className="sc-spin"/> Saving…</>:<><Clock3 size={16}/> Update delivery status</>}</button>
      </div>}
    </article>})}</div>
  </Container></div>;
}
