import { BellRing, CheckCircle2, Loader2, Mail, MessageCircle, Smartphone } from "lucide-react";
import { useEffect, useState } from "react";
import Container from "../components/shared/Container";
import { getDeliveryNotificationPreferences, updateDeliveryNotificationPreferences, type DeliveryNotificationPreferences } from "../services/deliveryNotificationPreferencesClient";

async function phoneVerify(action:"start"|"check",code?:string){const response=await fetch("/api/delivery-phone-verification",{method:"POST",credentials:"same-origin",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({action,code})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||"Phone verification failed.");return payload;}

export default function DeliveryNotificationPreferencesPage(){
  const[prefs,setPrefs]=useState<DeliveryNotificationPreferences|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[verifying,setVerifying]=useState(false);const[codeSent,setCodeSent]=useState(false);const[code,setCode]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
  useEffect(()=>{let active=true;getDeliveryNotificationPreferences().then(({preferences})=>{if(active)setPrefs(preferences)}).catch((err:any)=>{if(active)setError(err?.message||"Notification preferences could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[]);
  async function save(next:DeliveryNotificationPreferences){setSaving(true);setError("");setNotice("");try{const result=await updateDeliveryNotificationPreferences({emailEnabled:next.emailEnabled,smsEnabled:next.smsEnabled,whatsappEnabled:next.whatsappEnabled});setPrefs(result.preferences);setNotice("Delivery notification preferences updated.");}catch(err:any){setError(err?.message||"Notification preferences could not be updated.");}finally{setSaving(false);}}
  async function sendCode(){setVerifying(true);setError("");setNotice("");try{await phoneVerify("start");setCodeSent(true);setNotice("Verification code sent to your account phone number.");}catch(err:any){setError(err?.message||"Verification code could not be sent.");}finally{setVerifying(false);}}
  async function verifyCode(){setVerifying(true);setError("");setNotice("");try{const result=await phoneVerify("check",code);if(result?.preferences)setPrefs(result.preferences);else{const refreshed=await getDeliveryNotificationPreferences();setPrefs(refreshed.preferences);}setCode("");setCodeSent(false);setNotice("Phone verified. SMS and WhatsApp can now be enabled.");}catch(err:any){setError(err?.message||"The verification code was not accepted.");}finally{setVerifying(false);}}
  if(loading)return <div className="demo-page"><Container className="demo-page-content"><div className="demo-empty"><Loader2 className="sc-spin"/><h2>Loading notification settings…</h2></div></Container></div>;
  if(!prefs)return <div className="demo-page"><Container className="demo-page-content"><div className="demo-empty"><BellRing/><h2>Notification settings unavailable</h2><p>{error}</p></div></Container></div>;
  const phoneVerified=Boolean(prefs.phoneVerifiedAt);
  return <div className="demo-page"><section className="demo-page-hero"><Container><span>Account settings</span><h1>Delivery notifications</h1><p>Choose how SmartCommerce should contact you about order preparation, dispatch, collection and delivery exceptions. In-app order tracking remains available regardless of these settings.</p></Container></section><Container className="demo-page-content"><section className="sc-notification-preferences">
    {!phoneVerified?<div className="sc-notification-preferences__verify"><Smartphone size={20}/><div><strong>Verify your phone</strong><span>SmartCommerce will use Twilio Verify to confirm the phone number already stored on your account. We do not store the OTP.</span>{codeSent?<div><input inputMode="numeric" autoComplete="one-time-code" placeholder="Verification code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,10))}/><button type="button" disabled={verifying||code.length<4} onClick={()=>void verifyCode()}>{verifying?"Checking…":"Verify code"}</button><button type="button" disabled={verifying} onClick={()=>void sendCode()}>Send another code</button></div>:<button type="button" disabled={verifying} onClick={()=>void sendCode()}>{verifying?"Sending…":"Send verification code"}</button>}</div></div>:<div className="sc-notification-preferences__verified"><CheckCircle2 size={18}/><div><strong>Phone verified</strong><span>SMS and WhatsApp can be enabled for this verified account number.</span></div></div>}
    <article><div><Mail size={20}/><div><strong>Email</strong><span>Transactional order and delivery updates.</span></div></div><label><input type="checkbox" checked={prefs.emailEnabled} disabled={saving} onChange={e=>void save({...prefs,emailEnabled:e.target.checked})}/><span>{prefs.emailEnabled?"On":"Off"}</span></label></article>
    <article><div><Smartphone size={20}/><div><strong>SMS</strong><span>{phoneVerified?"Text-message delivery updates.":"Phone verification is required before SMS can be enabled."}</span></div></div><label><input type="checkbox" checked={prefs.smsEnabled} disabled={saving||!phoneVerified} onChange={e=>void save({...prefs,smsEnabled:e.target.checked})}/><span>{prefs.smsEnabled?"On":"Off"}</span></label></article>
    <article><div><MessageCircle size={20}/><div><strong>WhatsApp</strong><span>{phoneVerified?"Approved WhatsApp order-status notifications.":"Phone verification and WhatsApp opt-in are required before this channel can be enabled."}</span></div></div><label><input type="checkbox" checked={prefs.whatsappEnabled} disabled={saving||!phoneVerified} onChange={e=>void save({...prefs,whatsappEnabled:e.target.checked})}/><span>{prefs.whatsappEnabled?"On":"Off"}</span></label></article>
    <div className="sc-notification-preferences__note"><CheckCircle2 size={18}/><div><strong>In-app tracking stays on.</strong><span>These controls only affect external messages. Your authenticated order-tracking timeline remains the source of truth.</span></div></div>
    {notice?<p role="status">{notice}</p>:null}{error?<p role="alert">{error}</p>:null}
  </section></Container></div>;
}
