import CourierDispatchPanel from '../couriers/CourierDispatchPanel';
import CourierDeliveryPanel from '../couriers/CourierDeliveryPanel';
import {useEffect,useState} from 'react';
import Button from '../shared/Button';
import {formatCourierMoney} from '../../lib/courierMoney';
import {courierPrivateRequest,downloadCourierDocument} from '../../lib/courierPrivate';
import {CourierClientError} from '../../lib/couriers';
import {useCourierMutation} from '../couriers/useCourierMutation';
import '../../styles/couriers.css';
export default function CourierSecurityPanel(){
  const [records,setRecords]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[canScan,setCanScan]=useState(false),[bank,setBank]=useState<any>(null),[scan,setScan]=useState<any>(null);
  const [handoverAvailable,setHandoverAvailable]=useState(false);
  const [token,setToken]=useState(()=>new URLSearchParams(location.hash.split('?')[1]||'').get('pickup')||'');
  const mutation=useCourierMutation<any>(c=>courierPrivateRequest(true,c),result=>{if(result.data)downloadCourierDocument(result);else if(result.bank)setBank(result.bank);else if(Array.isArray(result.orders)){setScan(result);setNotice('Pickup pass checked.');}else{setSelected(null);setBank(null);setScan(null);setNotice(result.status==='collected'?`Order ${result.orderNumber} marked collected.`:'Request processed.');void load();}});
  async function load(next?:string){setLoading(true);setError('');try{const page=await courierPrivateRequest(true,undefined,next);setRecords(r=>next?[...r,...page.records]:page.records);setCursor(page.nextCursor);setCanScan(page.canScan===true);setHandoverAvailable(page.handoverAvailable===true);}catch(e){setError(e instanceof CourierClientError?e.message:'Courier reviews could not be loaded.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const locked=loading||mutation.busy||mutation.pending;
  return <div className="courier-page"><span className="courier-eyebrow">Courier operations</span><h2>Courier records</h2><p>Courier identity and business documents are verified in the POS. Documents, bank verification and payout decisions are read-only here; POS review is not connected yet.</p><p>Access is limited to your verification, payments and branch pickup permissions.</p>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {canScan&&!handoverAvailable&&<p role="status">Pickup QR validation and handover remain unavailable until POS verification is connected.</p>}
    {canScan&&handoverAvailable&&<section className="courier-card"><h3>Find the courier’s pickup orders</h3><p>Scan the courier QR with your device camera to open this page, or enter the pickup code. Only assigned orders at your authorized branches appear.</p><form onSubmit={e=>{e.preventDefault();setScan(null);void mutation.execute({action:'scan_pass',token:token.trim()});}}><label>Pickup code<input value={token} onChange={e=>{setToken(e.target.value);setScan(null);}} required maxLength={43} disabled={locked}/></label><Button type="submit" disabled={locked}>Validate pass & find orders</Button></form>
      {scan&&<><p>{scan.driverName} · {scan.organizationName}</p><p>Pass expires {new Date(scan.expiresAt).toLocaleString()}.</p>{!scan.orders.length?<p>No orders ready for this driver at your authorized branches. Do not release goods without an assigned order.</p>:scan.orders.map((order:any)=><article className="courier-row" key={order.id}><h3>Order {order.orderNumber}</h3><p>Branch: {order.branchId} · {order.status}</p><ul>{order.items.map((item:any,index:number)=><li key={index}>{item.name} {item.sku?`(${item.sku})`:''} — quantity {item.quantity}</li>)}</ul><h3>Delivery destination</h3><dl>{Object.entries(order.destination).filter(([,value])=>typeof value==='string').map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl><p>Check the driver and all listed items before confirming handover.</p><Button disabled={locked} onClick={()=>void mutation.execute({action:'confirm_pickup',id:order.id,expectedVersion:order.version,token:token.trim()})}>Confirm all items handed over</Button></article>)}</>}
    </section>}
    <Button variant="secondary" disabled={locked} onClick={()=>{setSelected(null);setBank(null);void load();}}>Refresh records</Button><div className="courier-layout"><section className="courier-card"><h3>Recorded documents and payouts</h3>{loading&&<p role="status">Loading…</p>}{!loading&&!records.length&&<p>No records available for your permissions.</p>}{records.map(r=><div className="courier-row" key={r.type+r.id}><Button variant="ghost" disabled={locked} onClick={()=>{setSelected(r);setBank(null);}}>{r.name||r.id} — {r.type}{r.kind?' / '+r.kind:''}</Button><span className="courier-status">{r.status.replaceAll('_',' ')}</span></div>)}{cursor&&<Button disabled={locked} onClick={()=>void load(cursor)}>Load more</Button>}</section>
    <section className="courier-card">{selected?<><h3>{selected.name||selected.id}</h3><p>{selected.type} · {selected.status.replaceAll('_',' ')}</p>{selected.type==='document'&&<Button variant="secondary" disabled={locked} onClick={()=>void mutation.execute({action:'read_document',id:selected.id})}>Download private document</Button>}{selected.type==='bank'&&<><p>{selected.masked}</p><Button variant="secondary" disabled={locked} onClick={()=>void mutation.execute({action:'read_bank',organizationId:selected.id})}>View private bank details</Button>{bank&&<dl>{Object.entries(bank).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>}</>}{selected.type==='payout'&&<><p>{formatCourierMoney(selected.amountMinor,selected.currency)}</p><Button variant="secondary" disabled={locked} onClick={()=>void mutation.execute({action:"read_payout_bank",id:selected.id})}>View recorded payout destination</Button>{bank&&<dl>{Object.entries(bank).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>}<p>Bank verification, payout approval and bank-transfer references are managed in the POS. POS synchronization is pending.</p></>}</>:<p>Select a record to review its details.</p>}</section></div>
    {canScan&&<CourierDispatchPanel staff/>}{canScan&&<CourierDeliveryPanel audience="staff"/>}{mutation.error&&<p role="alert">{mutation.error}</p>}{mutation.pending&&<Button disabled={mutation.busy} onClick={()=>void mutation.execute()}>Retry same request</Button>}
  </div>;
}
