import { Download, FileSpreadsheet, Printer, RefreshCw, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { reportingRequest, type OperationsApiError, type StaffIdentity } from "../../lib/staffOperations";
import "../../styles/reporting-center.css";

type Row = Record<string, any>;
type ReportKey =
  | "sales" | "inventory" | "nonmoving" | "slowmoving" | "damage" | "offledger"
  | "movements" | "transfers" | "purchasing" | "vendors" | "rentals" | "repairs"
  | "quotes" | "drawers" | "returns" | "cyclecounts" | "commissions" | "layaway";

type ReportDefinition = { key: ReportKey; label: string; group: string; description: string };
const REPORTS: ReportDefinition[] = [
  { key: "sales", label: "Sales", group: "Commercial", description: "Completed sales, tender mix and daily performance." },
  { key: "inventory", label: "Inventory", group: "Inventory", description: "Stock value, low stock and branch inventory position." },
  { key: "nonmoving", label: "Non-moving items", group: "Inventory", description: "Items with stock but no verified sales in the selected window." },
  { key: "slowmoving", label: "Slow-moving items", group: "Inventory", description: "Items with low recent movement relative to stock held." },
  { key: "damage", label: "Damaged / write-off", group: "Inventory", description: "Damage, disposal and write-off stock reductions from the movement ledger." },
  { key: "offledger", label: "Stock removed without sale", group: "Audit", description: "Negative inventory adjustments not represented as completed sales." },
  { key: "movements", label: "Inventory movements", group: "Inventory", description: "Manual adjustments and transfer movement evidence." },
  { key: "transfers", label: "Branch transfers", group: "Supply Chain", description: "Transfer lifecycle, quantities requested/received and discrepancies." },
  { key: "purchasing", label: "Purchasing & receiving", group: "Supply Chain", description: "Purchase requests, purchase orders and receiving status." },
  { key: "vendors", label: "Vendor / supplier items", group: "Supply Chain", description: "Supplier-linked stock, sales movement and aging-by-no-sale evidence." },
  { key: "rentals", label: "Rentals", group: "Rental", description: "Rental agreements, overdue items, balances, damage and utilization evidence." },
  { key: "repairs", label: "Repairs", group: "Service", description: "Work-order status, overdue repairs, branch and service performance." },
  { key: "quotes", label: "Quotations", group: "Commercial", description: "Quote status, value, acceptance and conversion." },
  { key: "drawers", label: "Cash drawers", group: "Audit", description: "Drawer sessions, reconciliation and over/short evidence." },
  { key: "returns", label: "Returns / refunds / voids", group: "Audit", description: "Transaction exceptions and reversal activity." },
  { key: "cyclecounts", label: "Cycle-count variances", group: "Audit", description: "Physical-count sessions and stock variance evidence." },
  { key: "commissions", label: "Commissions", group: "Workforce", description: "Commission records generated by the POS." },
  { key: "layaway", label: "Layaway", group: "Commercial", description: "Layaway agreements and payment status." },
];

const money = (value: unknown) => new Intl.NumberFormat("en-JM", { style: "currency", currency: "JMD", maximumFractionDigits: 2 }).format(Number(value) || 0);
const number = (value: unknown) => new Intl.NumberFormat("en-JM", { maximumFractionDigits: 2 }).format(Number(value) || 0);
const text = (value: unknown) => value == null || value === "" ? "—" : String(value);
const label = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const dateOnly = (value: Date) => value.toISOString().slice(0, 10);
const escapeCsv = (value: unknown) => { const s = value == null ? "" : String(value); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; };
const safeFile = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function download(filename: string, type: string, content: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url; anchor.download = filename; document.body.appendChild(anchor); anchor.click(); anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function asRows(value: unknown): Row[] {
  if (Array.isArray(value)) return value as Row[];
  if (!value || typeof value !== "object") return [];
  for (const key of ["rows", "items", "data", "adjustments", "transfers", "lowStock", "byCustomer"]) {
    const child = (value as Row)[key]; if (Array.isArray(child)) return child;
  }
  return [];
}

function flatten(prefix: string, value: unknown, target: Row) {
  if (value == null || typeof value !== "object") { target[prefix] = value; return; }
  if (Array.isArray(value)) { target[prefix] = value.map((item) => typeof item === "object" ? JSON.stringify(item) : String(item)).join(" | "); return; }
  for (const [key, child] of Object.entries(value as Row)) flatten(prefix ? `${prefix}.${key}` : key, child, target);
}

function exportableRows(rows: Row[]) { return rows.map((row) => { const flat: Row = {}; flatten("", row, flat); return flat; }); }

function canExport(staff: StaffIdentity) {
  if (Object.prototype.hasOwnProperty.call(staff.permissions, "reports_export")) return staff.permissions.reports_export === true;
  return staff.permissions.reports === true;
}

async function loadReport(key: ReportKey, start: string, end: string, branchId: string) {
  const branch = branchId ? `&branch_id=${encodeURIComponent(branchId)}` : "";
  if (key === "sales") {
    const data = await reportingRequest<any>(`reports/sales?start=${start}&end=${end}${branch}`);
    const rows = (Array.isArray(data?.byDay) ? data.byDay : []).map((row: Row) => ({ date: row.date, transactions: row.transactions, sales: row.sales }));
    return { rows, summary: data?.summary || {}, secondary: Array.isArray(data?.byMethod) ? data.byMethod : [] };
  }
  if (key === "inventory") {
    const data = await reportingRequest<any>(`reports/inventory?${branchId ? `branch_id=${encodeURIComponent(branchId)}` : ""}`);
    return { rows: Array.isArray(data?.lowStock) ? data.lowStock : [], summary: data?.summary || {}, secondary: Array.isArray(data?.byCategory) ? data.byCategory : [] };
  }
  if (["nonmoving", "slowmoving", "vendors"].includes(key)) {
    const [products, recent, suppliers] = await Promise.all([
      reportingRequest<Row[]>(`inventory?active=1&is_service=0&is_non_inventory=0${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`),
      reportingRequest<Row[]>(`reports/top-products?start=${start}&end=${end}&limit=5000${branch}`),
      reportingRequest<Row[]>("suppliers"),
    ]);
    const sold = new Map((Array.isArray(recent) ? recent : []).map((row) => [String(row.sku || ""), Number(row.units_sold || 0)]));
    const supplierById = new Map((Array.isArray(suppliers) ? suppliers : []).map((row) => [String(row.id), row]));
    const joined = (Array.isArray(products) ? products : []).map((row) => ({
      sku: row.sku, product: row.name, supplier: supplierById.get(String(row.supplier_id || ""))?.name || "Unassigned",
      stock_qty: Number(row.stock_qty || 0), min_stock: Number(row.min_stock || 0), cost: Number(row.cost || 0), price: Number(row.price || 0),
      units_sold: sold.get(String(row.sku || "")) || 0,
      stock_value: Number(row.stock_qty || 0) * Number(row.cost || 0),
    }));
    const days = Math.max(1, Math.ceil((new Date(`${end}T00:00:00Z`).getTime() - new Date(`${start}T00:00:00Z`).getTime()) / 86400000) + 1);
    const enriched = joined.map((row) => ({ ...row, daily_velocity: row.units_sold / days, days_of_cover: row.units_sold > 0 ? row.stock_qty / (row.units_sold / days) : null }));
    if (key === "nonmoving") return { rows: enriched.filter((row) => row.stock_qty > 0 && row.units_sold === 0).sort((a, b) => b.stock_value - a.stock_value), summary: {} };
    if (key === "slowmoving") return { rows: enriched.filter((row) => row.stock_qty > 0 && row.units_sold > 0 && (row.days_of_cover || 0) >= 90).sort((a, b) => (b.days_of_cover || 0) - (a.days_of_cover || 0)), summary: {} };
    return { rows: enriched.sort((a, b) => String(a.supplier).localeCompare(String(b.supplier)) || b.stock_value - a.stock_value), summary: {} };
  }
  if (["damage", "offledger", "movements"].includes(key)) {
    const data = await reportingRequest<any>(`inventory/movements?limit=1000${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`);
    const adjustments = Array.isArray(data?.adjustments) ? data.adjustments : [];
    if (key === "damage") return { rows: adjustments.filter((row: Row) => Number(row.quantity_change) < 0 && /(damage|write.?off|disposal|scrap|broken)/i.test(String(row.reason || row.type || ""))), summary: {} };
    if (key === "offledger") return { rows: adjustments.filter((row: Row) => Number(row.quantity_change) < 0), summary: {} };
    return { rows: [...adjustments.map((row: Row) => ({ movement_kind: "adjustment", ...row })), ...(Array.isArray(data?.transfers) ? data.transfers.map((row: Row) => ({ movement_kind: "transfer", ...row })) : [])], summary: {} };
  }
  if (key === "transfers") return { rows: await reportingRequest<Row[]>("transfers?limit=500"), summary: {} };
  if (key === "purchasing") {
    const [prs, pos] = await Promise.all([reportingRequest<Row[]>("purchase-requests?limit=500"), reportingRequest<Row[]>("purchase-orders?limit=500")]);
    return { rows: [...(Array.isArray(prs) ? prs.map((row) => ({ record_type: "Purchase Request", ...row })) : []), ...(Array.isArray(pos) ? pos.map((row) => ({ record_type: "Purchase Order", ...row })) : [])], summary: {} };
  }
  if (key === "rentals") return { rows: await reportingRequest<Row[]>(`rentals/agreements?${branchId ? `branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "repairs") return { rows: await reportingRequest<Row[]>(`work-orders?limit=500${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "quotes") return { rows: await reportingRequest<Row[]>(`quotations?limit=500${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "drawers") return { rows: await reportingRequest<Row[]>(`drawers/sessions?limit=500${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "returns") return { rows: await reportingRequest<Row[]>(`transactions?limit=500${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "cyclecounts") return { rows: await reportingRequest<Row[]>(`warehouse/cycle-counts?limit=500${branchId ? `&branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  if (key === "commissions") return { rows: await reportingRequest<Row[]>("commissions"), summary: {} };
  if (key === "layaway") return { rows: await reportingRequest<Row[]>(`layaway?${branchId ? `branch_id=${encodeURIComponent(branchId)}` : ""}`), summary: {} };
  return { rows: [], summary: {} };
}

function visibleColumns(rows: Row[]) {
  const priority = ["record_type", "date", "created_at", "transaction_number", "agreement_number", "work_order_number", "quote_number", "po_number", "pr_number", "transfer_number", "sku", "product", "product_name", "name", "supplier", "supplier_name", "branch_name", "from_branch_name", "to_branch_name", "customer_name", "status", "display_status", "quantity_change", "stock_qty", "units_sold", "days_of_cover", "total", "sales", "balance_due", "reason"];
  const keys = new Set<string>(); rows.slice(0, 50).forEach((row) => Object.keys(row).forEach((key) => { if (typeof row[key] !== "object") keys.add(key); }));
  const ordered = [...priority.filter((key) => keys.has(key)), ...[...keys].filter((key) => !priority.includes(key)).sort()];
  return ordered.slice(0, 14);
}

export default function ReportingCenter({ staff }: { staff: StaffIdentity }) {
  const today = new Date(); const startDefault = new Date(today.getTime() - 29 * 86400000);
  const [report, setReport] = useState<ReportKey>("sales");
  const [start, setStart] = useState(dateOnly(startDefault)); const [end, setEnd] = useState(dateOnly(today));
  const [branchId, setBranchId] = useState(""); const [branches, setBranches] = useState<Row[]>([]);
  const [rows, setRows] = useState<Row[]>([]); const [secondary, setSecondary] = useState<Row[]>([]); const [summary, setSummary] = useState<Row>({});
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const definition = REPORTS.find((item) => item.key === report)!;

  async function load() {
    setLoading(true); setError("");
    try { const result = await loadReport(report, start, end, branchId); setRows(Array.isArray(result.rows) ? result.rows : []); setSummary(result.summary || {}); setSecondary(Array.isArray(result.secondary) ? result.secondary : []); }
    catch (e) { setRows([]); setSummary({}); setSecondary([]); setError((e as OperationsApiError).message || "This report could not be loaded."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void reportingRequest<Row[]>("branches").then((value) => setBranches(Array.isArray(value) ? value : [])).catch(() => setBranches([])); }, []);
  useEffect(() => { void load(); }, [report]);

  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase(); if (!needle) return rows;
    return rows.filter((row) => Object.values(row).some((value) => typeof value !== "object" && String(value ?? "").toLowerCase().includes(needle)));
  }, [rows, query]);
  const columns = useMemo(() => visibleColumns(filtered), [filtered]);

  function csvExport() {
    const flat = exportableRows(filtered); const headers = [...new Set(flat.flatMap(Object.keys))];
    const csv = [headers.map(escapeCsv).join(","), ...flat.map((row) => headers.map((key) => escapeCsv(row[key])).join(","))].join("\r\n");
    download(`${safeFile(definition.label)}-${start}-to-${end}.csv`, "text/csv;charset=utf-8", `\uFEFF${csv}`);
  }
  function excelExport() {
    const flat = exportableRows(filtered); const headers = [...new Set(flat.flatMap(Object.keys))];
    const esc = (v: unknown) => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const html = `<!doctype html><html><head><meta charset="utf-8"></head><body><table><thead><tr>${headers.map((h) => `<th>${esc(label(h))}</th>`).join("")}</tr></thead><tbody>${flat.map((row) => `<tr>${headers.map((h) => `<td>${esc(row[h])}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`;
    download(`${safeFile(definition.label)}-${start}-to-${end}.xls`, "application/vnd.ms-excel;charset=utf-8", html);
  }
  function printReport() { window.print(); }

  return <section className="sc-reporting-center" data-guide-id="reporting-center">
    <aside className="sc-reporting-center__nav">
      <div><strong>Reporting Center</strong><span>If the POS records it, it should be reportable.</span></div>
      {[...new Set(REPORTS.map((item) => item.group))].map((group) => <section key={group}><h3>{group}</h3>{REPORTS.filter((item) => item.group === group).map((item) => <button key={item.key} type="button" className={report === item.key ? "is-active" : ""} onClick={() => setReport(item.key)}>{item.label}</button>)}</section>)}
    </aside>
    <div className="sc-reporting-center__main">
      <header className="sc-reporting-center__header">
        <div><span>{definition.group}</span><h2>{definition.label}</h2><p>{definition.description}</p></div>
        <div className="sc-reporting-center__actions">
          {canExport(staff) ? <><button type="button" onClick={csvExport} disabled={!filtered.length}><Download size={16}/>CSV</button><button type="button" onClick={excelExport} disabled={!filtered.length}><FileSpreadsheet size={16}/>Excel</button></> : null}
          <button type="button" onClick={printReport} disabled={!filtered.length}><Printer size={16}/>Print / PDF</button>
        </div>
      </header>
      <div className="sc-reporting-center__filters">
        <label>From<input type="date" value={start} max={end} onChange={(e) => setStart(e.target.value)} /></label>
        <label>To<input type="date" value={end} min={start} onChange={(e) => setEnd(e.target.value)} /></label>
        <label>Branch<select value={branchId} onChange={(e) => setBranchId(e.target.value)}><option value="">All permitted branches</option>{branches.map((branch) => <option key={String(branch.id)} value={String(branch.id)}>{branch.name || branch.branch_name || branch.id}</option>)}</select></label>
        <button type="button" onClick={() => void load()} disabled={loading}><RefreshCw size={16}/>{loading ? "Loading…" : "Run report"}</button>
        <label className="sc-reporting-center__search"><Search size={15}/><input placeholder="Search report" value={query} onChange={(e) => setQuery(e.target.value)} /></label>
      </div>

      <div className="sc-reporting-center__print-heading"><strong>Total Tools Rental & Electrical Supplies Limited</strong><span>{definition.label} · {start} to {end}</span></div>
      {Object.keys(summary).length ? <div className="sc-reporting-center__summary">{Object.entries(summary).filter(([, value]) => typeof value !== "object").slice(0, 8).map(([key, value]) => <article key={key}><span>{label(key)}</span><strong>{/sales|total|value|tax|discount|order/i.test(key) && typeof value === "number" ? money(value) : text(value)}</strong></article>)}</div> : null}
      {error ? <div className="sc-reporting-center__empty is-error"><strong>Report unavailable</strong><p>{error}</p></div> : loading ? <div className="sc-reporting-center__empty"><strong>Loading live POS evidence…</strong></div> : !filtered.length ? <div className="sc-reporting-center__empty"><strong>No matching records</strong><p>No sample rows are inserted into reports.</p></div> : <div className="sc-reporting-center__table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{label(column)}</th>)}</tr></thead><tbody>{filtered.map((row, index) => <tr key={String(row.id ?? row.transaction_number ?? row.sku ?? index)}>{columns.map((column) => <td key={column}>{/amount|total|sales|revenue|cost|price|value|balance|fee/i.test(column) && Number.isFinite(Number(row[column])) ? money(row[column]) : /qty|quantity|units|count|days_of_cover|velocity/i.test(column) && Number.isFinite(Number(row[column])) ? number(row[column]) : text(row[column])}</td>)}</tr>)}</tbody></table></div>}
      {secondary.length ? <details className="sc-reporting-center__secondary"><summary>Supporting breakdown ({secondary.length})</summary><pre>{JSON.stringify(secondary, null, 2)}</pre></details> : null}
      <footer className="sc-reporting-center__footer"><span>{filtered.length} report rows</span><span>Generated from live POS evidence · {new Date().toLocaleString()}</span></footer>
    </div>
  </section>;
}
