import CourierDispatchPanel from './CourierDispatchPanel';
import CourierDeliveryPanel from './CourierDeliveryPanel';
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {formatCourierMoney} from '../../lib/courierMoney';
import Button from '../shared/Button';
import {courierPrivateRequest} from '../../lib/courierPrivate';
import {useCourierMutation} from './useCourierMutation';
import {CourierClientError} from '../../lib/couriers';
export default function CourierPrivatePanel({organizationId}:{organizationId?:string}){
  const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[qr,setQr]=useState(''),[pass,setPass]=useState<any>(null),[invite,setInvite]=useState('');
  async function load(){try{setState(await courierPrivateRequest());setError('');}catch(e){setError(e instanceof CourierClientError?e.message:'Private courier details could not be loaded.');}}
  useEffect(()=>{void load();},[organizationId]);
  const mutation=useCourierMutation<any>(command=>courierPrivateRequest(false,command),result=>{setNotice('Saved.');if(result.token&&result.expiresAt){setPass(result);const url=location.origin+location.pathname+'#/operations/courier-security?pickup='+encodeURIComponent(result.token);void QRCode.toDataURL(url,{width:280,margin:3,errorCorrectionLevel:'M'}).then(setQr).catch(()=>setError('The pass was issued, but its QR could not be rendered. Issue a replacement pass.'));}else if(result.token)setInvite(result.token);else{setPass(null);setQr('');}void load();});
  const locked=busy||mutation.busy||mutation.pending;
  async function upload(kind:string,file:File|undefined,version:number){if(!file)return;if(file.size>2*1024*1024){setError('Choose a PDF, JPEG or PNG file no larger than 2 MB.');return;}setBusy(true);setError('');try{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error());r.readAsDataURL(file);});await mutation.execute({action:'upload_document',id:crypto.randomUUID(),kind,mime:file.type,data,expectedVersion:version});}catch{setError('The document could not be read. Choose the file again.');}finally{setBusy(false);}}
  return <section><h2>Verification, drivers & payments</h2>{error&&<p role="alert">{error}</p>}{!state?<Button onClick={()=>void load()}>Load private details</Button>:<>
    <div className="courier-layout"><section className="courier-card"><h3>Identity verification</h3><p>Documents are private and reviewed by authorized staff. Replacing a document requires a new review.</p>{(organizationId?['identity','business']:['identity']).map(kind=>{const doc=state.documents.find((d:any)=>d.kind===kind);return <div className="courier-row" key={kind}><label>{kind==='identity'?'Identity document':'Business document'}<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={locked} onChange={e=>{void upload(kind,e.target.files?.[0],doc?.version||0);e.target.value='';}}/></label><span className="courier-status">{doc?.status||'Not uploaded'}</span>{doc?.reason&&<p>{doc.reason}</p>}</div>;})}<p>PDF, JPEG or PNG; maximum 2 MB each.</p></section>
    <section className="courier-card"><h3>Your driver membership</h3>{state.membership?<><p>{state.membership.businessName}</p><span className="courier-status">{state.membership.active?'Active member':'Inactive member'}</span><p>Your identity and the courier business must be verified and approved before you can receive a pickup pass.</p><div className="courier-actions"><Button disabled={locked||!state.membership.active} onClick={()=>void mutation.execute({action:'issue_pass'})}>Issue a pickup QR</Button><Button variant="secondary" disabled={locked} onClick={()=>void mutation.execute({action:'revoke_pass'})}>Revoke pickup pass</Button></div>{qr&&<><img src={qr} width={280} height={280} style={{maxWidth:'100%',height:'auto'}} alt="Your individual pickup QR code"/><p>Expires {new Date(pass.expiresAt).toLocaleString()}. Keep this pass private. A replacement revokes the previous pass.</p></>}</>:<><p>Enter the invitation code from your courier company. Your SmartCommerce email must be verified before accepting.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutation.execute({action:'accept_invite',id:crypto.randomUUID(),token:String(f.get('token')).trim()});}}><label>Driver invitation code<input name="token" required maxLength={43} disabled={locked}/></label><Button type="submit" disabled={locked}>Join courier company</Button></form><a href="#/account">Manage email verification</a></>}</section></div>
    {organizationId&&<><section className="courier-card"><h3>Your drivers</h3><p>Invite each driver by their account email. They sign in separately and upload their own identity document.</p><form className="courier-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutation.execute({action:'invite_driver',organizationId,email:String(f.get('email'))});}}><label>Driver email<input name="email" type="email" required maxLength={254} disabled={locked}/></label><Button type="submit" disabled={locked}>Create driver invitation</Button></form>{invite&&<p className="courier-note">Share this code privately with the invited driver. It expires after 48 hours: <code style={{overflowWrap:'anywhere'}}>{invite}</code></p>}{state.drivers.map((d:any)=><div className="courier-row" key={d.id}><strong>{d.name}</strong><p>Identity: {d.verification} · {d.active?'Active':'Inactive'}</p>{d.active&&<Button variant="secondary" disabled={locked} onClick={()=>void mutation.execute({action:'remove_driver',organizationId,id:d.id,expectedVersion:d.version})}>Remove driver</Button>}</div>)}</section>
    <section className="courier-card"><h3>Bank-transfer payout details</h3><p>Staff verify these details before approving payouts. Saving changes puts them back into review.</p>{state.bank&&<p>{state.bank.masked} · {state.bank.status}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const bank=Object.fromEntries(['bankName','accountName','accountNumber','routing','currency'].map(k=>[k,String(f.get(k)||'').trim()]));void mutation.execute({action:'save_bank',organizationId,expectedVersion:state.bank?.version||0,bank});}}><fieldset className="courier-fields" disabled={locked}><div className="courier-grid">{[['bankName','Bank name'],['accountName','Account holder'],['accountNumber','Account number'],['routing','Branch / routing details'],['currency','Currency code']].map(([name,label])=><label key={name}>{label}<input name={name} required={name!=='routing'} maxLength={name==='currency'?3:150} pattern={name==='currency'?'[A-Z]{3}':undefined} autoComplete="off"/></label>)}</div><Button type="submit">Save bank details for review</Button></fieldset></form></section>
    <section className="courier-card"><h3>Earnings & payouts</h3><p>Only earnings from verified paid bookings and accepted delivery evidence can become payable. Payout approval does not transfer money.</p>{!state.earnings.length&&<p>No recorded delivery earnings. Booking and delivery settlement are not connected yet.</p>}{state.earnings.map((e:any)=><div className="courier-row" key={e.currency+e.status}><strong>{formatCourierMoney(e.amountMinor,e.currency)} · {e.status}</strong>{e.status==='payable'&&<Button disabled={locked} onClick={()=>void mutation.execute({action:'request_payout',id:crypto.randomUUID(),organizationId,currency:e.currency})}>Request payout</Button>}</div>)}{state.payouts.map((p:any)=><div className="courier-row" key={p.id}><strong>{formatCourierMoney(p.amountMinor,p.currency)}</strong><p>{p.status.replaceAll('_',' ')}{p.transferReference?' · Reference '+p.transferReference:''}</p></div>)}</section></>}
    </>}{state&&organizationId&&<CourierDispatchPanel drivers={state.drivers}/>}{state&&<CourierDeliveryPanel audience="courier"/>}{mutation.error&&<p role="alert">{mutation.error}</p>}{mutation.pending&&<Button disabled={mutation.busy} onClick={()=>void mutation.execute()}>Retry same request</Button>}{notice&&<p role="status">{notice}</p>}
  </section>;
}
